sudo: required
language: node_js

services: 
  - docker

before_install:
  - docker build -t gginis/docker-react -f Dockerfile.dev . 

script:
  - docker run gginis/docker-react npm run test -- --coverage
  
